POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog 6 - With user3",
  "author": "Tester",
  "url": "www.example.com",
  "likes": 3,
  "userId": "6846d8a09a001035a2b1ebaf"
}
