POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2ODQ2ZDg5NDlhMDAxMDM1YTJiMWViYWMiLCJpYXQiOjE3NDk0NzY4Nzh9.r23z9pB-ZnwQDPmxVwCg_kzCmD4YXnAmEDup_uCN_gM

{
  "title": "Test Blog 8 - testing 4.20*: Blog List Expansion, step 8",
  "author": "Tester",
  "url": "www.example.com",
  "likes": 3,
  "userId": "6846d8a09a001035a2b1ebaf"
}
